/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bleedTokenSol from "./BleedToken.sol";
export type { bleedTokenSol };
export type { Playground } from "./Playground";
export type { ThrottledWallet } from "./ThrottledWallet";
